// Builds the BrewPack release timeline that powers /releases.
//
// This is deliberately a SEPARATE scan from the catalog importer and the
// quick/full discovery scanners. Those read the "fresh beer" collection, which
// only ever contains what is on sale right now. A release timeline needs the
// opposite: every pack Pinter has ever listed, including seasonals that are
// currently off the shelf. So this reads the whole store product feed instead,
// and falls back to fetching individual product records for packs the feed
// omits.
//
// The dates this produces are ESTIMATES, not announcements. All of the rules
// for deriving and qualifying them live in scripts/lib/release-history.ts,
// which is pure and unit tested. This file is only fetching and file writing.

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { brewPacks } from "../data/brewpacks.generated";
import { fetchJsonWithRetry } from "./lib/http";
import {
  assertTimelineSafe,
  buildRelease,
  findBulkCreationDays,
  normalizeName,
  selectPackProducts,
  sortReleases,
  type BrewPackRelease,
  type StoreProduct,
} from "./lib/release-history";

// The whole store, not a single collection. Includes hardware, gift cards and
// merch, which selectPackProducts filters out.
const storeFeedUrl = (page: number): string =>
  `https://pinter.com/products.json?limit=250&page=${page}`;

// A single product record, for packs missing from the store feed.
const productUrl = (handle: string): string =>
  `https://pinter.com/products/${handle}.json`;

const OUTPUT_FILE = path.join(process.cwd(), "data", "releases.generated.ts");

/** Safety stop so a feed that never returns an empty page cannot loop forever. */
const MAX_FEED_PAGES = 10;

/**
 * Packs whose store handle is not just their catalog id. Seasonals live outside
 * the store feed, so we fetch them by handle and need the exact spelling.
 */
const HANDLE_OVERRIDES: Record<string, string> = {
  prostmeister: "prostmeister-oktoberfest-lager",
};

/** Shop title -> catalog name, mirroring scripts/import-brewpacks.ts. */
const SHOP_NAME_ALIASES: Record<string, string> = {
  Snap: "Snap Pilsner",
  "Deep Shade Coffee": "Deep Shade",
  "Lagunitas Sumpin' Easy Remixed": "Sumpin' Easy Remixed",
};

/** Page through the store feed until it stops returning products. */
async function fetchAllStoreProducts(): Promise<StoreProduct[]> {
  const products: StoreProduct[] = [];

  for (let page = 1; page <= MAX_FEED_PAGES; page += 1) {
    const body = await fetchJsonWithRetry<{ products?: StoreProduct[] }>(
      storeFeedUrl(page),
    );

    if (!Array.isArray(body.products)) {
      throw new Error(
        "Pinter store feed did not contain a products array — source layout may have changed.",
      );
    }

    if (body.products.length === 0) break;

    products.push(...body.products);
  }

  return products;
}

/** Fetch one product record, or null when the handle does not resolve. */
async function fetchProduct(handle: string): Promise<StoreProduct | null> {
  try {
    const body = await fetchJsonWithRetry<{ product?: StoreProduct }>(
      productUrl(handle),
      { retries: 1 },
    );
    return body.product ?? null;
  } catch {
    // A 404 here is expected and meaningful: the pack is not on the store at
    // all, so it simply has no date. Not an error worth failing the run for.
    return null;
  }
}

function formatRelease(release: BrewPackRelease): string {
  const list = (values: string[]): string =>
    values.length === 0
      ? "[]"
      : `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;

  return `  {
    id: ${JSON.stringify(release.id)},
    name: ${JSON.stringify(release.name)},
    style: ${JSON.stringify(release.style)},
    abv: ${release.abv},
    releaseDate: ${JSON.stringify(release.releaseDate)},
    precision: ${JSON.stringify(release.precision)},
    reissuedOn: ${JSON.stringify(release.reissuedOn)},
    status: ${JSON.stringify(release.status)},
    imageUrl: ${JSON.stringify(release.imageUrl)},
    blurb: ${JSON.stringify(release.blurb)},
    flavors: ${list(release.flavors)},
    badges: ${list(release.badges)},
  }`;
}

export function buildGeneratedFile(releases: BrewPackRelease[]): string {
  return `// This file is generated by scripts/release-scan.ts.
// Do not edit manually.
//
// Dates are ESTIMATES derived from Shopify product timestamps, not official
// release announcements. See scripts/lib/release-history.ts for how each date
// is chosen and why some are month-only.

export type ReleasePrecision = "day" | "month" | "unknown";

export type BrewPackRelease = {
  id: string;
  name: string;
  style: string;
  abv: number;
  releaseDate: string | null;
  precision: ReleasePrecision;
  reissuedOn: string | null;
  status: "available" | "unavailable" | "discontinued";
  imageUrl: string | null;
  blurb: string | null;
  flavors: string[];
  badges: string[];
};

export const releases: BrewPackRelease[] = [
${releases.map(formatRelease).join(",\n")}
];
`;
}

// The generated file is written atomically (temp file + rename) so a crash
// mid-write can never leave a truncated or empty timeline on disk.
async function writeGeneratedFile(releases: BrewPackRelease[]): Promise<void> {
  await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });

  const tempFile = `${OUTPUT_FILE}.tmp`;
  await writeFile(tempFile, buildGeneratedFile(releases), "utf8");
  await rename(tempFile, OUTPUT_FILE);
}

async function main(): Promise<void> {
  console.log("Building BrewPack release timeline.");
  console.log(`  Store feed: ${storeFeedUrl(1)}\n`);

  const storeProducts = await fetchAllStoreProducts();

  // Index the store feed by normalized catalog name so we can join it to the
  // curated pack list.
  const byName = new Map<string, StoreProduct>();
  for (const product of selectPackProducts(storeProducts)) {
    const canonical = SHOP_NAME_ALIASES[product.title] ?? product.title;
    byName.set(normalizeName(canonical), product);
  }

  // Resolve every pack to a product first, because spotting bulk creation days
  // needs the whole set before any release can be dated.
  const resolved: Array<{
    pack: (typeof brewPacks)[number];
    product: StoreProduct | null;
  }> = [];
  let recovered = 0;

  for (const pack of brewPacks) {
    let product = byName.get(normalizeName(pack.name)) ?? null;

    // Seasonals and retired packs are absent from the store feed but usually
    // still have a reachable product record. That record is the only surviving
    // evidence of when they first appeared, so it is worth the extra request.
    if (!product) {
      const handle = HANDLE_OVERRIDES[pack.id] ?? pack.id;
      product = await fetchProduct(handle);
      if (product) recovered += 1;
    }

    resolved.push({ pack, product });
  }

  const bulkCreationDays = findBulkCreationDays(
    resolved.map(({ product }) => product),
  );

  const releases = sortReleases(
    resolved.map(({ pack, product }) =>
      buildRelease(pack, product, bulkCreationDays),
    ),
  );

  assertTimelineSafe(releases);
  await writeGeneratedFile(releases);

  const reissued = releases.filter((release) => release.reissuedOn).length;
  const undated = releases.filter((release) => !release.releaseDate);

  console.log(
    `Wrote ${releases.length} packs to data/releases.generated.ts ` +
      `(${recovered} recovered off-feed, ${reissued} look re-released).`,
  );

  if (undated.length > 0) {
    console.log(
      `No date found for: ${undated.map((release) => release.name).join(", ")}`,
    );
  }
}

// Only run the scan when this file is executed directly (pnpm scan:releases),
// not when something imports its helpers.
const isDirectRun =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error("\nRelease scan failed.");
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
